# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: osx_build
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run build:osx
      npm run pack:osx
    displayName: 'npm install and build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'drop-osx'
      targetPath: .dist

- job: win_build
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: npm install && npm run build:win && npm run pack:win
    displayName: 'npm install and build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'drop-win'
      targetPath: .dist