# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: osx_build
    pool:
      vmImage: 'macOS-10.14'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          cd packages/electron-shell
          npm install
          npm run dist:osx
        displayName: 'npm install, pack, and dist'
      - task: CopyFiles@2
        inputs:
          Contents: 'dist/*.dmg'
          TargetFolder: 'drop'
          flattenFolders: true
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'drop-osx'
          targetPath: drop

  - job: win_build
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: cd packages\electron-shell\
        displayName: 'change directory to electron-shell'
      - script: npm install && npm run dist:win
        displayName: 'npm install, pack, and dist'
      - task: CopyFiles@2
        inputs:
          Contents: 'dist\*.exe'
          TargetFolder: 'drop'
          flattenFolders: true
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'drop-win'
          targetPath: drop

  - job: github_release
    dependsOn:
      - osx_build
      - win_build
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          targetPath: '.\github-release-assets'
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: 'chuanqisun'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'manual'
          tag: 'vX.Y.Z'
          title: 'vX.Y.Z'
          assets: '.\github-release-assets\**\*'
          releaseNotesSource: 'input'
          releaseNotes: |
            === Replace me with release notes ===
          isDraft: true
          addChangeLog: false
